server:
  port: 8002
spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          auto-add-partitions: true
          min-partition-count: 1
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
          group: test
      bindings:
        kafkaMessage-out-0:
          destination: test
          group: kafka-test-group
          content-type: text/plain
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/be

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.openfeign: info
    org.springframework.cloud.sleuth: info
client:
  serviceUrl: http://localhost:8001
config:
  file-lock: D:\\workspace\\project\\be-code-challenge\\lock
  num: 2
