spring:
  application:
    name: be-register
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    register-with-eureka: false
    enableSelfPreservation: true
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: health,loggers
