server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://be-register/eureka/
logging:
  level:
    org.springframework.cloud.openfeign: info
    org.springframework.cloud.sleuth: info